# Generated by Django 5.2 on 2025-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameForge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameconcept',
            name='title',
        ),
        migrations.AddField(
            model_name='gameconcept',
            name='description',
            field=models.TextField(default=85),
            preserve_default=False,
        ),
    ]
