# Generated by Django 5.2 on 2025-04-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameForge', '0002_remove_gameconcept_title_gameconcept_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyact',
            name='title',
            field=models.TextField(),
        ),
    ]
