# Generated by Django 5.2 on 2025-04-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameForge', '0004_gameconcept_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameconcept',
            old_name='description',
            new_name='title',
        ),
    ]
